baseURL = "https://kevinstarry.github.io"
languageCode = "zh-cn"
DefaultContentLanguage = "en"
hasCJKLanguage = true
enableGitInfo = true  
title = ""
theme = "anatole"
summarylength = 20
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "悠然时光，愿爱长存"
author = "KevinStarry"
description = "心念所往之，则万千无惧"
profilePicture = "images/profile.jpg"
keywords = "博客"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post","emotion"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.


[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kevinstarry"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:2552712328@qq.com"

## Menu items

[menu]

  [[menu.main]]
  name = "首页"
  identifier = "home"
  weight = 10
  url = "/"

  [[menu.main]]
  name = "教程学习"
  weight = 20
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "情绪感悟"
  weight = 30
  identifier = "emotion"
  url = "/emotion/"

  [[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "其他"
  weight = 50
  identifier = "other"
  url = "/other/"

